# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Portfolio"
license = "MIT"
licenselink = "https://github.com/tbauer516/Portfolio-v3/blob/master/LICENSE"
description = "Portfolio page for Tyler Bauer, a passionate software developer"
homepage = "https://tylerbauer.info"
tags = ["", ""]
features = ["", ""]
min_version = 0.15

[author]
  name = "Tyler Bauer"
  homepage = "https://tylerbauer.info"